name: TownsAndNations-pl3xmap
version: '${version}'
main: org.leralix.tanpl3xmap.TownsAndNationsPl3xmap
api-version: '1.19'
depend:  [TownsAndNations, Pl3xMap]
commands:
  tanmap:
    description: Town and Nation dynmap command
    permission: townandnation_pl3xmap.base
    usage: /<command>
  tanmapAdmin:
    description: Town and Nation dynmap admin command
    permission: townandnation_pl3xmap.admin
    usage: /<command>