# Common configuration options
# To update the config please restart the server.

update:
  # Seconds between checks for map update
  period: 300

#Set the maximum number of points to be used for polygons
#If the polygon is too large, a straight line will close it to the first point.
#If increasing this value does not help, please contact us on discord.
polygon_max_points: 100000


# Territory Layer (Towns, Regions and Nations)
chunk_layer:
  # Name of the layer
  name: "Towns and Nations"
  # List of worlds to show on the map
  # use "all" to show all worlds
  worlds:
    #  - "world"
    #  - "world_nether"
    #  - "world_the_end"
    - "all"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  priority: 10
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0

#Landmarks layer
landmark_layer:
  # Name of the layer
  name: "Towns and Nations - Landmarks"
  # List of worlds to show on the map
  # use "all" to show all worlds
  worlds:
    #  - "world"
    #  - "world_nether"
    #  - "world_the_end"
    - "all"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  priority: 5
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0

#Landmarks layer
fort_layer:
  # Name of the layer
  name: "Towns and Nations - Forts"
  # List of worlds to show on the map
  # use "all" to show all worlds
  worlds:
    #  - "world"
    #  - "world_nether"
    #  - "world_the_end"
    - "all"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in layer menu (low goes before high - default is 0)
  priority: 5
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0

  #Property layer
  property_layer:
    # Name of the layer
    name: "Towns and Nations - Properties"
    # List of worlds to show on the map
    # use "all" to show all worlds
    worlds:
      #  - "world"
      #  - "world_nether"
      #  - "world_the_end"
      - "all"
    # Make the layer hidden by default
    hide_by_default: false
    # ordering priority in layer menu (low goes before high - default is 0)
    priority: 9
    # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
    minimum_zoom: 0

propertiesColor:
    owned: "#FFA500" # Orange
    for_rent: "#89CFF0" # Blue
    rented: "#ff0000" # Red
    for_sale: "#008000" # Green


# Format for info windows
# Use %<FLAG_NAME>% for placeholders

# %TOWN_NAME% - Name of the town
# %DAYS_SINCE_CREATION% - Number of days since the town or region was created
# %DESCRIPTION% - Description of the town or region
# %NUMBER_CLAIMS% - Number of claims in the town or region
# %TOWN_LEADER% - Leader of the town
# %TOWN_LEVEL% - Level of the town
# %MEMBERS_LIST% - List of members in the town

town_infowindow: "<div style=\"white-space: nowrap\"><div class=\"infowindow\"><span style=\"font-size:140%;font-weight:bold;\">%TOWN_NAME%</span>  <span style=\"font-size:80%\">Created %DAYS_SINCE_CREATION% day(s) ago</span><br><br><span style=\"font-size:100%;font-style:italic;\">%DESCRIPTION%</span><br><hr><span style=\"font-size:100%;\"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Level</b> %TOWN_LEVEL% </span><hr><br><span style=\"font-weight:bold;\">Region:</span><br>%REGION_NAME%<br><br><span style=\"font-weight:bold;\">Leader</span><br>%TOWN_LEADER%<br><br><span style=\"font-weight:bold;\">Members</span><br>%MEMBERS_LIST%<br></div></div>"

# %REGION_NAME% - Name of the region
# %DAYS_SINCE_CREATION% - Number of days since the town or region was created
# %DESCRIPTION% - Description of the town or region
# %NUMBER_CLAIMS% - Number of claims in the town or region
# %NUMBER_OF_TOWNS% - Number of towns in the region
# %TOWN_LIST% - List of towns in the region
# %REGION_CAPITAL% - Capital of the region


region_infowindow: "<div style=\"white-space: nowrap\"><div class=\"infowindow\"> <span style=\"font-size:140%;font-weight:bold;\">%REGION_NAME%</span>  <span style=\"font-size:80%\">Created %DAYS_SINCE_CREATION% day(s) ago</span><br><br><span style=\"font-size:100%;font-style:italic;\">%DESCRIPTION%</span><br><hr><span style=\"font-size:100%;\"><b>Claims</b> %NUMBER_CLAIMS% <b>|</b> <b>Number of towns</b> %NUMBER_OF_TOWNS% </span><hr><br><span style=\"font-weight:bold;\">Capital</span><br>%REGION_CAPITAL%<br><br><span style=\"font-weight:bold;\">Towns</span><br>%TOWN_LIST%<br></div></div>"

# %LANDMARK_NAME% - Name of the landmark
# %OWNER% - Owner of the landmark.
# %QUANTITY%x - Quantity of the item being produced.
# %ITEM% - Item being produced.
landmark_infowindow: "<div style=\"white-space: nowrap\"><div class=\"infowindow\"><span style=\"font-size:140%;font-weight:bold;\">%LANDMARK_NAME%</span><span style=\"font-size:100%;font-style:italic;\"><br><hr><span style=\"font-size:100%;\"><b>Owner</b></span><br>%OWNER%</div><b>Producing<br></b> %QUANTITY%x %ITEM%</span></div>"

#%FORT_NAME% - Name of the fort.
#%OWNER% - Owner of the landmark.
#%OCCUPIER% - Occupier of the fort.
fort_infowindow: "<div style=\"white-space: nowrap; display: inline-block;\"><div class=\"infowindow\" style=\"display: inline-block;\"><span style=\"font-size:140%; font-weight:bold;\">%FORT_NAME%</span><br><hr><span style=\"margin-left: 10px; font-size:100%;\"><b>Owner:</b>%OWNER% <b>|</b> <b>Occupied by:</b> %OCCUPIER%</span></div></div>"

# %PROPERTY_NAME% - Name of the property
# %PROPERTY_DESCRIPTION% - Name of the property
# %PROPERTY_OWNER% - Name of the property owner
# %STATUS% - Status of the property (Owned, For Rent, Rented by..., For Sale)
property_infowindow: "<div style=\"white-space: nowrap\"><div class=\"infowindow\"><span style=\"font-size:140%;font-weight:bold;\">%PROPERTY_NAME%</span></span><br><br><span style=\"font-size:100%;font-style:italic;\">%PROPERTY_DESCRIPTION%</span><br><hr><span style=\"font-size:100%;\"><span>Owned by :</b> %PROPERTY_OWNER%</span><br>Status :  <span>%STATUS% </span></div></div>"