name: TownsAndNations-bluemap
version: '${version}'
main: org.leralix.tanbluemap.TownsAndNationsBluemap
api-version: '1.19'
depend:  [TownsAndNations, BlueMap]
commands:
  tanmap:
    description: Town and Nation dynmap command
    permission: townandnation_bluemap.base
    usage: /<command>
  tanmapAdmin:
    description: Town and Nation dynmap admin command
    permission: townandnation_bluemap.admin
    usage: /<command>